# Recommended values:
# PlantTime: 5 to 10 seconds
# DetonationTime: 25 to 45 seconds
# DefuseTime: 5 to 10 seconds
#   # For fairness, it's recommended that PlantTime = DefuseTime
# TimerSound: 
#   # 1.9: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
#   # 1.8: http://rainbowcraft.sytes.net/javadocs/bukkit/1.8/org/bukkit/Sound.html
# BombBlock: 
#   # 1.9: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
#   # 1.8: http://rainbowcraft.sytes.net/javadocs/bukkit/1.8/org/bukkit/Material.html
# BaseBlock: (Any Block with an Inventory):
#          : ANVIL, BEACON, BREWING_STAND
#          : CHEST, ENDER_CHEST, TRAPPED_CHEST
#          : ENCHANTMENT_TABLE, DISPENSER, DROPPER
#          : FURNACE, HOPPER, WORKBENCH
# ExplosionMaxDamage: 50 # DMG = MAX - (DELTA * DISTANCE)
# ExplosionDeltaDamage: 5 # DMG = MAX - (DELTA * DISTANCE)
# ExplosionRadius: 8
#  # Distance to Damage Table:
#  # DISTANCE:   0   1   2   3   4   5   6   7   8   9   10   11
#  # DAMAGE:     50  45  40  35  30  25  20  15  10  0   0    0
#     As you can see: according to this table,
#     the default killzone is 6 blocks from the base eventho the bomb does dmg up to 8 blocks away.
#     And 9 blocks does NOT do 5 dmg because the Radius is set to 8.
# StartupDisplay: (integer) The number of ranks to print to the console during server startup.
# DatabaseTable: '' This is the name of the table.
#      # This name does NOT include the prefix & suffix that BattleTracker uses.
#      # Exampe: 'Bomb' will show up in the database as
#      # bt_Bomb_overall
#      # bt_Bomb_tally
#      # bt_Bomb_versus
# ShowHolograms: true/false
#   # http://dev.bukkit.org/bukkit-plugins/holographic-displays/
#   # http://dev.bukkit.org/bukkit-plugins/holoapi/
# Debug: true or false
#   # true = debugging mode ON
#   # false = debugging mode OFF
#   # cmd toggle: /bomb debug
PlantTime: 6
DetonationTime: 40
DefuseTime: 6
TimerSound: ENTITY_EXPERIENCE_ORB_PICKUP
BombBlock: TNT
BaseBlock: BREWING_STAND
BaseRadius: 3
MaxDamage: 50
DeltaDamage: 5
DamageRadius: 9
StartupDisplay: 3
DatabaseTable: BombArena
ShowHolograms: true
Debug: false
