# Anticipated Configuration Options.
# Some options may not be implemented depending on your version.
# 
# Recommended values:
# PlantTime: 5 to 10 seconds
# DetonationTime: 25 to 45 seconds
# DefuseTime: 1 # Number of Times that the BombBlock must be destroyed in order to be defused.
#               # Recommend one for most blocks.
#               # Recommend for TNT is about 4 per second.
#               # So if you want TNT and you also want a 10 second defuse timer, then 
#               # set DefuseTime: 40
#               # 4 times 10 = 40
# Tolerance: 100 to 600 milliseconds
#     # This MAX time allowed inbetween Block Breaks (defusing the bomb).
#     # If this number is too small, it will be impossible to defuse the bomb.
#     # If this number is too large, then players will be able to 
#       # stop defusing the bomb for the specificed number of milliseconds 
#       # and perform other actions (like killing players)
#       # and then go back to their previous Bomb Defusal attempt.
# BombBlock: HARD_CLAY x1 is recommended. Or SPONGE x4. Or TNT x35
#            # Approximate Time to destroy one block:
#            # You can find the times at the bottom of this config.yml
# BaseBlock: (Any Block with an Inventory):
#          : ANVIL, BEACON, BREWING_STAND
#          : CHEST, ENDER_CHEST, TRAPPED_CHEST
#          : ENCHANTMENT_TABLE, DISPENSER, DROPPER
#          : FURNACE, HOPPER, WORKBENCH
#     ### DO NOT CHANGE FakePlayerName:
#     ### use ChangeFakePlayerName: 'New Name' to let the plugin make changes to the database.
# FakeName: "Bombs Planted Defuse", "Bomb Totals"
# ChangeFakeName: ''
# ExplosionMaxDamage: 50 # DMG = MAX - (DELTA * DISTANCE)
# ExplosionDeltaDamage: 5 # DMG = MAX - (DELTA * DISTANCE)
# ExplosionRadius: 8
# ### Distance to Damage Table:
# ### DISTANCE:   0   1   2   3   4   5   6   7   8   9   10   11
# ### DAMAGE:     50  45  40  35  30  25  20  15  10  0   0    0
#     As you can see: according to this table,
#     the default killzone is 6 blocks from the base eventho the bomb does dmg up to 8 blocks away.
#     And 9 blocks does NOT do 5 dmg because the Radius is set to 8.
# StartupDisplay: (integer) The number of ranks to print to the console during server startup.
# DatabaseTable: '' This is the name of the table.
#      # This name does NOT include the prefix & suffix that BattleTracker uses.
#      # Exampe: 'Bomb' will show up in the database as
#      # bt_Bomb_overall
#      # bt_Bomb_tally
#      # bt_Bomb_versus
# BreakTimes: DO NOT CHANGE THOSE VALUES (measures are in milliseconds)
#      # EXAMPLE: 2999 ms = 2.9 seconds
#      # You can use this section to find a block and it's break time
#        # and use the BLOCK_NAME for the BombBlock: section
#      # use cmd (/bomb record) to add new blocks & times.
#      # or to change existing values.
PlantTime: 8
DetonationTime: 35
DefuseTime: 35
Tolerance: 500
BombBlock: TNT
BaseBlock: BREWING_STAND
FakeName: 'Bombs Planted Defused'
ChangeFakeName: ''
MaxDamage: 50
DeltaDamage: 5
DamageRadius: 9
StartupDisplay: 3
DatabaseTable: 'Demolition'
BreakTimes:
  TNT: 0
  LEAVES: 249
  GLOWSTONE: 350
  GLASS: 450
  REDSTONE_LAMP_OFF: 450
  PACKED_ICE: 550
  SOUL_SAND: 650
  HAY_BLOCK: 650
  PISTON_STICKY_BASE: 699
  CACTUS: 700
  GRAVEL: 750
  MYCEL: 750
  ICE: 750
  PISTON_BASE: 750
  SPONGE: 800
  SAND: 850
  GRASS: 850
  DIRT: 850
  CLAY: 950
  WOOL: 1000
  NOTE_BLOCK: 1050
  SNOW_BLOCK: 1200
  JACK_O_LANTERN: 1400
  PUMPKIN: 1449
  MELON_BLOCK: 1600
  NETHERRACK: 2000
  BOOKSHELF: 2200
  WOOD: 2994
  LOG: 2999
  JUKEBOX: 3000
  QUARTZ_BLOCK: 3900
  SANDSTONE: 4000
  HARD_CLAY: 6198
  STAINED_CLAY: 6199
  SMOOTH_BRICK: 7499
  STONE: 7500
  NETHER_BRICK: 10000
  BRICK: 10050
  MOSSY_COBBLESTONE: 10050
  COBBLESTONE: 10099
  GLOWING_REDSTONE_ORE: 14850
  EMERALD_ORE: 14949
  QUARTZ_ORE: 14999
  LAPIS_ORE: 15099
  LAPIS_BLOCK: 15001
  GOLD_BLOCK: 15000
  ENDER_STONE: 15049
  DIAMOND_ORE: 15100
  ENDER_PORTAL_FRAME: 15400
  DIAMOND_BLOCK: 24949
  EMERALD_BLOCK: 24999
  IRON_BLOCK: 24999
  REDSTONE_BLOCK: 25000
  COAL_BLOCK: 25098
